name: Auto comment on new issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    if: contains(github.event.issue.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### Проверьте две вещи:
            - вы на последней версии: [Releases](https://github.com/Flowseal/tg-ws-proxy/releases)
            - запускали по инструкции для своей ОС: [Быстрый старт](https://github.com/Flowseal/tg-ws-proxy#навигация)

            ## Решение частых проблем:

            **Q**: Не запускается, падает с ошибкой, не работает как раньше после обновления?  
            **A**:
            1. Удалите всё в папке Temp (или хотя бы всё, что начинается с _MEI) 
            2. Запускайте от имени админа
            3. Попробуйте Win7 версию (если вы пользователь Windows)
            4. Попробуйте отключить антивирус (если помогло, то добавьте exe в исключения). Не забудьте включить антивирус обратно.

            ###

            **Q**: Не грузит медиа? (фото/видео/стикеры)  
            **A**: Удалите в настройках прокси в поле **DC → IP** всё, кроме `4:149.154.167.220`. Если это не помогло, полностью очистите это поле.


            #### Если проблема решена, то закройте Issue

            ### Если проблема осталась, пожалуйста, приложите по возможности логи.
            Сделать это можно через иконку в трее -> Пкм -> Открыть логи. Сохраните логи в файл и приложите его сюда.
